name: Build and test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  test_stable:
    name: Stable
    strategy:
      matrix:
        toolchain:
          - 1.75.0 # MSRV
          - 1.86.0
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: cargo build --verbose
      - run: cargo clippy -- --deny warnings
      - run: cargo clippy --tests -- --deny warnings
      - run: cargo test

  test_nightly:
    name: Nightly
    strategy:
      matrix:
        toolchain:
          - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - run: rustup component add miri
      - run: cargo build --verbose
      - run: cargo clippy -- --deny warnings
      - run: cargo clippy --tests -- --deny warnings
      - run: cargo test
      - run: cargo miri test

# vim: ts=2 sw=2 expandtab
